platform :ios, '13.0'

target 'Upgrade' do
  use_frameworks!
  inhibit_all_warnings!

  pod 'Hero'
  pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :tag => '5.1.10-beta.0'

end
