name: Build Xcode project

on: [push, pull_request]

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Install Cocoapods
        run: |
          sudo gem install cocoapods
      - name: Install dependencies
        run: |
          cd ../..
          cd Upgrade/
          pod install
      - name: Build project
        run: |
          xcodebuild -workspace "Upgrade.xcworkspace" -scheme "Upgrade"
